# -*- coding: utf-8 -*-
"""Projeto_Web_Mining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdP20CMpZB1FIlcMe0d3Y-HggwpbYFfT
"""

pip install chart_studio

import numpy as np
import pandas as pd
#import plotly.plotly as py
import chart_studio.plotly as py
#from plotly.offline import init_notebook_mode,iplot
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
import plotly.graph_objects as go
from plotly import tools
import warnings
warnings.filterwarnings("ignore")

"""***Nesta base, examinamos os tweets de pessoas com opinião política democrática e republicana.***"""

#Carregando a base de Tweets Democratas e Republicanos
tweets_dem_rep = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Tweet/ExtractedTweets.csv')
base_tweets.head(10)

tweets_dem_rep.Party.value_counts()

tweets_handles = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Tweet/TwitterHandles.csv')
tweets_handles.head(10)

tweets_handles.Party.value_counts()

"""# **E o primeiro tweet é:**"""

tweets_dem_rep.Tweet[0]

"""# **1- LIMPEZA DE DADOS**

**Antes de iniciar a análise, devemos remover objetos como @, rt, html, # etc.**
"""

import re
import nltk
from nltk.corpus import stopwords
import nltk as nlp
stopwords = stopwords.words('english')
#adicione alguma palavra desnecessária à lista de stopwords
stopwords.append("rt")
stopwords.append("u")
stopwords.append("amp")
stopwords.append("w")
stopwords.append("th")

#Criamos 2 classes diferentes como democratas e republicanas
democrat=tweets_dem_rep[tweets_dem_rep.Party=="Democrat"]
republican=tweets_dem_rep[tweets_dem_rep.Party=="Republican"]

#Limpeza de Tweets do partido democrata 
democrat_list=[]
for d in democrat.Tweet:
    d=re.sub(r'http\S+', '', d) #remover links
    d=re.sub("[^a-zA-Z]", " ", d) #remove todos os caracteres, exceto letras
    d=d.lower() #converter todas as palavras em minúsculas
    d=nltk.word_tokenize(d) #dividir frases em palavras
    d=[word for word in d if not word in set(stopwords)] #adicione à lista de palavras irrelevantes se palavras desnecessárias.
    lemma=nlp.WordNetLemmatizer() 
    d=[lemma.lemmatize(word) for word in d] #identifique a forma correta da palavra no dicionário
    d=" ".join(d)
    democrat_list.append(d) #acrescentar palavras à lista

#Limpeza de Tweets do partido republicano
republican_list=[]
for r in republican.Tweet:
    r=re.sub(r'http\S+', '', r)#remover links
    r=re.sub("[^a-zA-Z]", " ", r)#remove todos os caracteres, exceto letras
    r=r.lower()#converter todas as palavras em minúsculas
    r=nltk.word_tokenize(r)#dividir frases em palavras
    r=[word for word in r if not word in set(stopwords)]#adicione à lista de palavras irrelevantes se palavras desnecessárias.
    lemma=nlp.WordNetLemmatizer()
    r=[lemma.lemmatize(word) for word in r]#identifique a forma correta da palavra no dicionário
    r=" ".join(r)
    republican_list.append(r)#acrescentar palavras à lista

"""### **Agora nossas listas são as seguintes**"""

#primeiros 5 tweets da lista
democrat_list[0:5]

#primeiros 5 tweets da lista
republican_list[0:5]

"""###Revizando tweets palavra por palavra.
Dividindo as frases em palavras, remover caracteres de pontuação desnecessários.
"""

democrat_tweets=str(democrat_list).split()
republican_tweets=str(republican_list).split()
democrat_tweets=[word.replace("'","") for word in democrat_tweets ]
democrat_tweets=[word.replace("[", "") for word in democrat_tweets ]
democrat_tweets=[word.replace("]","") for word in democrat_tweets ]
democrat_tweets=[word.replace(",", "") for word in democrat_tweets ]

republican_tweets=[word.replace("'","") for word in republican_tweets ]
republican_tweets=[word.replace("[", "") for word in republican_tweets ]
republican_tweets=[word.replace("]","") for word in republican_tweets ]
republican_tweets=[word.replace(",", "") for word in republican_tweets ]

"""**Agora vamos verificar o comprimento de duas listas.**"""

print("Democrat tweets word length:",len(democrat_tweets))
print("Republican tweets word length:",len(republican_tweets))

"""**Existem 443138 palavras em tuítes democratas e 457293 palavras em tuítes republicanos.**

# **2- Frequência de Uso de Palavras pelas Partes**
"""

#FreqDist registra o número de vezes que cada palavra é usada.
from nltk.probability import FreqDist
fdist_democrat = FreqDist(democrat_tweets)
fdist_republican=FreqDist(republican_tweets)

fdist_democrat

"""**Por exemplo, a palavra "hoje" (3850 vezes) é mais usada nos tweets enviados por democratas. Em segundo lugar, "trunfo" (2502) e em terceiro lugar "americano".**"""

fdist_republican

"""**Se olharmos para os tweets de pessoas que têm uma opinião republicana, a palavra "hoje" (4883 vezes) está em primeiro lugar novamente. "imposto" está em segundo lugar e "ótimo", em terceiro.**

***Nos gráficos a seguir, as 30 palavras mais utilizadas foram apresentadas de acordo com a opinião política.***
"""

import matplotlib.pyplot as plt
plt.subplots(figsize=(10,5))
fdist_democrat.plot(30,title="Democrat Tweets")
plt.subplots(figsize=(10,5))
fdist_republican.plot(30,title="Republican Tweets")

"""***Para analisar melhor, mesclo as duas listas e as frequências de palavras usadas no dataframe.***"""

de=pd.DataFrame(list(fdist_democrat.items()), columns = ["Word","FrequencyDemocrat"])
re=pd.DataFrame(list(fdist_republican.items()), columns = ["Word","FrequencyRepublican"])
nova_base=pd.merge(de,re,on='Word')

nova_base.head(10)

"""**Também categorizei as frequências de palavras em 5 grupos.**

1. Se uma palavra for usada com menos de 50, ela está no grupo muito baixo.

2. Se for usado entre 50 e 150 vezes, está no grupo baixo.

3. Se for usado entre 150 e 500 vezes, está no grupo médio.

4. Se for usado entre 500 e 1.500 vezes, está no grupo alto.

5. Se o uso de uma palavra for maior que 1.500, ela está no grupo muito alto.

**Também adicionei essas novas listas ao novo dataframe.**
"""

democratclass=[] 
for each in nova_base.FrequencyDemocrat:
    if each<50:
        democratclass.append("Muito baixo")
    elif 49<each<150:
        democratclass.append("Baixo")
    elif 149<each<500:
        democratclass.append("Médio")
    elif 499<each<1500:
        democratclass.append("Alto")
    else:
        democratclass.append("Muito alto")
        
nova_base["democratclass"]=democratclass

republicanclass=[] 
for each in nova_base.FrequencyRepublican:
    if each<50:
        republicanclass.append("Muito baixo")
    elif 49<each<150:
        republicanclass.append("Baixo")
    elif 149<each<500:
        republicanclass.append("Médio")
    elif 499<each<1500:
        republicanclass.append("Alto")
    else:
        republicanclass.append("Muito alto")
        
nova_base["republicanclass"]=republicanclass

nova_base.head(10)

democratMuitoAlto=nova_base[nova_base.democratclass=="Muito alto"]
democratAlto=nova_base[nova_base.democratclass=="Alto"]
democratMédio=nova_base[nova_base.democratclass=="Médio"]
democratBaixo=nova_base[nova_base.democratclass=="Baixo"]
democratMuitoBaixo=nova_base[nova_base.democratclass=="Muito baixo"]

vhvh=democratMuitoAlto[nova_base.republicanclass=="Muito alto"]
vhh=democratMuitoAlto[nova_base.republicanclass=="Alto"]
vhm=democratMuitoAlto[nova_base.republicanclass=="Médio"]
vhl=democratMuitoAlto[nova_base.republicanclass=="Baixo"]
vhvl=democratMuitoAlto[nova_base.republicanclass=="Muito baixo"]

hvh=democratAlto[nova_base.republicanclass=="Muito alto"]
hh=democratAlto[nova_base.republicanclass=="Alto"]
hm=democratAlto[nova_base.republicanclass=="Médio"]
hl=democratAlto[nova_base.republicanclass=="Baixo"]
hvl=democratAlto[nova_base.republicanclass=="Muito baixo"]

mvh=democratMédio[nova_base.republicanclass=="Muito alto"]
mh=democratMédio[nova_base.republicanclass=="Alto"]
mm=democratMédio[nova_base.republicanclass=="Médio"]
ml=democratMédio[nova_base.republicanclass=="Baixo"]
mvl=democratMédio[nova_base.republicanclass=="Muito baixo"]

lvh=democratBaixo[nova_base.republicanclass=="Muito alto"]
lh=democratBaixo[nova_base.republicanclass=="Alto"]
lm=democratBaixo[nova_base.republicanclass=="Médio"]
ll=democratBaixo[nova_base.republicanclass=="Baixo"]
lvl=democratBaixo[nova_base.republicanclass=="Muito baixo"]

vlvh=democratMuitoBaixo[nova_base.republicanclass=="Muito alto"]
vlh=democratMuitoBaixo[nova_base.republicanclass=="Alto"]
vlm=democratMuitoBaixo[nova_base.republicanclass=="Médio"]
vll=democratMuitoBaixo[nova_base.republicanclass=="Baixo"]
vlvl=democratMuitoBaixo[nova_base.republicanclass=="Muito baixo"]

"""**Criação de categorias para criar uma matriz.**"""

trace5 = go.Scatter(y=vhvh.FrequencyDemocrat, x=vhvh.FrequencyRepublican,text=vhvh.Word,mode='markers+text')
trace4 = go.Scatter(y=vhh.FrequencyDemocrat, x=vhh.FrequencyRepublican,text=vhh.Word,mode='markers+text')
trace3 = go.Scatter(y=vhm.FrequencyDemocrat, x=vhm.FrequencyRepublican,text=vhm.Word,mode='markers+text')
trace2 = go.Scatter(y=vhl.FrequencyDemocrat, x=vhl.FrequencyRepublican,text=vhl.Word,mode='markers+text')
trace1 = go.Scatter(y=vhvl.FrequencyDemocrat, x=vhvl.FrequencyRepublican,text=vhvl.Word,mode='markers+text')

trace10 = go.Scatter(y=hvh.FrequencyDemocrat, x=hvh.FrequencyRepublican,text=hvh.Word,mode='markers+text')
trace9 = go.Scatter(y=hh.FrequencyDemocrat, x=hh.FrequencyRepublican,text=hh.Word,mode='markers+text')
trace8 = go.Scatter(y=hm.FrequencyDemocrat, x=hm.FrequencyRepublican,text=hm.Word,mode='markers+text')
trace7 = go.Scatter(y=hl.FrequencyDemocrat, x=hl.FrequencyRepublican,text=hl.Word,mode='markers+text')
trace6 = go.Scatter(y=hvl.FrequencyDemocrat, x=hvl.FrequencyRepublican,text=hvl.Word,mode='markers+text')

trace15 = go.Scatter(y=mvh.FrequencyDemocrat, x=mvh.FrequencyRepublican,text=mvh.Word,mode='markers+text')
trace14 = go.Scatter(y=mh.FrequencyDemocrat, x=mh.FrequencyRepublican,text=mh.Word,mode='markers+text')
trace13 = go.Scatter(y=mm.FrequencyDemocrat, x=mm.FrequencyRepublican,text=mm.Word,mode='markers+text')
trace12 = go.Scatter(y=ml.FrequencyDemocrat, x=ml.FrequencyRepublican,text=ml.Word,mode='markers+text')
trace11 = go.Scatter(y=mvl.FrequencyDemocrat, x=mvl.FrequencyRepublican,text=mvl.Word,mode='markers+text')


trace20 = go.Scatter(y=lvh.FrequencyDemocrat, x=lvh.FrequencyRepublican,text=lvh.Word,mode='markers+text')
trace19 = go.Scatter(y=lh.FrequencyDemocrat, x=lh.FrequencyRepublican,text=lh.Word,mode='markers+text')
trace18 = go.Scatter(y=lm.FrequencyDemocrat, x=lm.FrequencyRepublican,text=lm.Word,mode='markers+text')
trace17 = go.Scatter(y=ll.FrequencyDemocrat, x=ll.FrequencyRepublican,text=ll.Word,mode='markers+text')
trace16 = go.Scatter(y=lvl.FrequencyDemocrat, x=lvl.FrequencyRepublican,text=lvl.Word,mode='markers+text')

trace25 = go.Scatter(y=vlvh.FrequencyDemocrat, x=vlvh.FrequencyRepublican,text=vlvh.Word,mode='markers+text')
trace24 = go.Scatter(y=vlh.FrequencyDemocrat, x=vlh.FrequencyRepublican,text=vlh.Word,mode='markers+text')
trace23 = go.Scatter(y=vlm.FrequencyDemocrat, x=vlm.FrequencyRepublican,text=vlm.Word,mode='markers+text')
trace22 = go.Scatter(y=vll.FrequencyDemocrat, x=vll.FrequencyRepublican,text=vll.Word,mode='markers+text')
trace21 = go.Scatter(y=vlvl.FrequencyDemocrat, x=vlvl.FrequencyRepublican,text=vlvl.Word,mode='markers+text')

fig = tools.make_subplots(rows=5, cols=5,shared_xaxes=True, shared_yaxes=True,print_grid=False)
#fig = chart_studio.plotly(rows=5, cols=5,shared_xaxes=True, shared_yaxes=True,print_grid=False)

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)
fig.append_trace(trace3, 1, 3)
fig.append_trace(trace4, 1, 4)
fig.append_trace(trace5, 1, 5)
fig.append_trace(trace6, 2, 1)
fig.append_trace(trace7, 2, 2)
fig.append_trace(trace8, 2, 3)
fig.append_trace(trace9, 2, 4)
fig.append_trace(trace10, 2, 5)
fig.append_trace(trace11, 3, 1)
fig.append_trace(trace12, 3, 2)
fig.append_trace(trace13, 3, 3)
fig.append_trace(trace14, 3, 4)
fig.append_trace(trace15, 3, 5)
fig.append_trace(trace16, 4, 1)
fig.append_trace(trace17, 4, 2)
fig.append_trace(trace18, 4, 3)
fig.append_trace(trace19, 4, 4)
fig.append_trace(trace20, 4, 5)
fig.append_trace(trace21, 5, 1)
fig.append_trace(trace22, 5, 2)
fig.append_trace(trace23, 5, 3)
fig.append_trace(trace24, 5, 4)
fig.append_trace(trace25, 5, 5)


fig['layout']['xaxis5'].update(title='Muito alto')
fig['layout']['xaxis4'].update(title='Alto')
fig['layout']['xaxis3'].update(title='Médio')
fig['layout']['xaxis2'].update(title='Baixo')
fig['layout']['xaxis1'].update(title='Muito Baixo')

fig['layout']['yaxis1'].update(title='Muito alto')
fig['layout']['yaxis2'].update(title='Alto')
fig['layout']['yaxis3'].update(title='Médio')
fig['layout']['yaxis4'].update(title='Baixo')
fig['layout']['yaxis5'].update(title='Muito Baixo')



fig['layout'].update(height=1500, width=1500, title= "Palavras em tweets democratas e republicanos",showlegend=False, titlefont=dict(size=30),
                    annotations=[dict(showarrow=False,text="Tweets Republicanos",x=0.5,y=-0.06,xref="paper",yref="paper",
                                      font=dict(size=30)),dict(showarrow=False, text='Tweets democrata',
                                                               x=-0.06,y=0.5,xref="paper",yref="paper",textangle=270,
                                                               font=dict(size=30))],
                    plot_bgcolor="snow" ,paper_bgcolor='rgb(243, 243, 243)')

iplot(fig)

"""**Nesta matriz,**

O eixo x mostra a frequência de uso de palavras de tuítes republicanos e o eixo y democratas.

Por exemplo, a palavra "reforma tributária" é usada pelo republicano 966 vezes (está na categoria alta) (e acho que é uma hashtag). No entanto, os democratas usaram essa palavra apenas 12 vezes.

O outro exemplo é a palavra "arma". É usado 876 vezes em tuítes democratas e 117 vezes em tuítes republicanos.

Também não há palavras, quando os republicanos usaram muito altamente e os democratas usaram no nível médio, baixo ou muito baixo. O mesmo que para os democratas.

As palavras "hoje", "americano", "ótimo," casa "," ano "," família "," dia "e" agradecer "são muito usadas tanto por democratas como republicanos.

Essas categorias são as categorias que criei. Diferentes classificações também podem ser feitas. Os intervalos de uso podem ser alterados.

# **3- Gráficos de Dispersão**

Selecionei algumas palavras no conjunto de dados e observei a distribuição de uso para ambas as partes.

Essas palavras são "voto", "democracia", "liberdade", "américa", "americana", "imposto", "trunfo" e "clinton".

Além disso, as outras palavras podem ser escolhidas.
"""

from nltk.text import Text  
democrat_tweet=Text(democrat_tweets)
republican_tweet=Text(republican_tweets)

"""Democratas Tweets Plot"""

plt.subplots(figsize=(10,5))
democrat_tweet.dispersion_plot(["vote","democracy","freedom","america","american","tax","trump","clinton"])

"""Republicanos Tweets Plot"""

plt.subplots(figsize=(10,5))
republican_tweet.dispersion_plot(["vote","democracy","freedom","america","american","tax","trump","clinton"])

"""# **4- Análise de sentimentos**

A pontuação de polaridade é uma flutuação dentro do intervalo [-1,0, 1,0]. E representa emoções expressas em uma frase. 1 significa afirmação positiva e -1 significa uma afirmação negativa.

A subjetividade é uma flutuação dentro do intervalo [0,0, 1,0] onde 0,0 é muito objetivo e 1,0 é muito subjetivo. E se refere à opinião pessoal, emoção ou julgamento.
"""

from textblob import TextBlob
democratblob=TextBlob(str(democrat_tweets))
republicanblob=TextBlob(str(republican_tweets))

"""**Usando o TextBlob, você pode ver as pontuações de polaridade e subjetividade de ambas as partes.**"""

democratblob.sentiment

republicanblob.sentiment

"""# **5- Classificação Naive Bayes**

Carregamos tudo em um Pandas DataFrame. (O conjunto de dados ExtractedTweets.csv consiste nos 200 tweets mais recentes, no momento da coleta de dados, de cada membro da Câmara dos Representantes dos EUA que possui uma conta no Twitter.)

Em seguida, obtemos uma divisão 80/20 dos identificadores do Twitter no conjunto de dados, estratificados de acordo com a variável Party. Dessa forma, teremos proporções aproximadamente semelhantes de democratas e republicanos nos conjuntos de treinamento e teste separadamente, como em todo o conjunto de dados. Por fim, dividimos o conjunto de dados completo em conjuntos de treinamento e teste com base nos identificadores do Twitter, pois não queremos que nenhum tweeter individual apareça nos conjuntos de treinamento e teste.
"""

import pandas as pd 

from nltk.tokenize.casual import TweetTokenizer

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

#inicializar o tokenizer
tokenizer = TweetTokenizer(reduce_len=True)

# Obtenha uma divisão de treinamento / teste de 80/20 dos identificadores do Twitter, estratificados no Party
tweeters = tweets_dem_rep.iloc[:,:2].drop_duplicates()
handles_train, handles_test = train_test_split(tweeters.Handle, stratify=tweeters.Party, test_size=0.2, random_state=0)

# extrair conjuntos de trem e teste de todos os tweets df
train = tweets_dem_rep[tweets_dem_rep.Handle.isin(handles_train)].reset_index().drop('index', axis=1)
test = tweets_dem_rep[tweets_dem_rep.Handle.isin(handles_test)].reset_index().drop('index', axis=1)

"""### **Construindo pipeline scikit-learn**
Vetorizador TF-IDF e um Classificador. O Vetorizador TF-IDF tokeniza o texto de cada tweet e, em seguida, calcula os pesos TF-IDF para os termos no tweet tokenizado.
"""

nb_pipeline = Pipeline([
    ('vectorize', TfidfVectorizer(tokenizer=tokenizer.tokenize)),
    ('classifier', MultinomialNB())
])

"""### **Treino e avaliação**
Treinar e avaliar o modelo resulta em 74,34% de precisão por tweet, o que não é tão ruim.
"""

nb_pipeline.fit(train.Tweet, train.Party)

preds = nb_pipeline.predict(test.Tweet)
print('Precisão: {}'.format(str(round(accuracy_score(test.Party, preds), 4))))

"""### **Avaliação por congressista**
Não é tão incomum que um único tweet seja mal categorizado, então talvez devêssemos considerar a categorização geral dos tweets de cada congressista. Com este ajuste, obtemos uma precisão de 94,25%, mesmo com este modelo muito simples.
"""

accuracy_df = test.drop(['Tweet'], axis=1)
accuracy_df['preds'] = preds
correct = 0
total = 0

print("Congressistas cujos tweets foram classificados incorretamente:")
for name in accuracy_df.Handle.unique():
    sub_df = accuracy_df[accuracy_df.Handle == name].reset_index()
    sub_preds = sub_df.preds.value_counts()

    if sub_preds.index[0] == sub_df.Party[0]:
        correct += 1
    total += 1

    if sub_preds[sub_df.Party[0]]/len(sub_df) < 0.5:
        print("{} ({}) classificado com precisão: {}".format(name, sub_df.Party[0],
                                                                      str(round(sub_preds[sub_df.Party[0]]/len(sub_df), 4))))

print()
print("A precisão do modelo por congressista foi: {}".format(str(round(correct/total, 4))))